# Generated by Django 4.1.3 on 2022-11-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
